/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliveries/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Deliveries */
        post: operations["retry_deliveries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Review */
        get: operations["list_review"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Review */
        post: operations["resolve_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Request */
        post: operations["route_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeseries */
        get: operations["timeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigResponse */
        ConfigResponse: {
            /** Data Source */
            data_source: ("public" | "synthetic" | "private") | null;
            /** Domain */
            domain: string | null;
            /** Examples */
            examples: string[];
            /** Labels */
            labels: components["schemas"]["LabelInfo"][];
            /** Target Type */
            target_type: string | null;
            /** Task */
            task: string | null;
            /** Tiers */
            tiers: components["schemas"]["TierInfo"][];
        };
        /** DeliveryCounts */
        DeliveryCounts: {
            /** Failed */
            failed: number;
            /** Pending */
            pending: number;
            /** Retryable */
            retryable: number;
            /** Sent */
            sent: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LabelInfo */
        LabelInfo: {
            /** Description */
            description: string | null;
            /** Name */
            name: string;
        };
        /** LatencyStats */
        LatencyStats: {
            /** Avg */
            avg: number;
            /** P95 */
            p95: number;
        };
        /** RequestItem */
        RequestItem: {
            /**
             * Action
             * @enum {string}
             */
            action: "accepted" | "human_review";
            /** Confidence */
            confidence: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Degraded */
            degraded: boolean;
            /** Delivered At */
            delivered_at: string | null;
            /** Delivery Error */
            delivery_error: string | null;
            /** Delivery Status */
            delivery_status: ("pending" | "sent" | "failed") | null;
            /** Final Label */
            final_label: string | null;
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Review Status */
            review_status: ("pending" | "resolved") | null;
            /** Text */
            text: string;
            /** Tier */
            tier: string | null;
        };
        /** RetryResult */
        RetryResult: {
            /** Failed */
            failed: number;
            /** Retried */
            retried: number;
            /** Sent */
            sent: number;
        };
        /** ReviewCounts */
        ReviewCounts: {
            /** Pending */
            pending: number;
            /** Resolved */
            resolved: number;
        };
        /** ReviewDecision */
        ReviewDecision: {
            /** Label */
            label: string;
        };
        /** ReviewItem */
        ReviewItem: {
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Suggested Label */
            suggested_label: string | null;
            /** Text */
            text: string;
            /** Tier */
            tier: string | null;
        };
        /** ReviewResolved */
        ReviewResolved: {
            /** Final Label */
            final_label: string;
            /** Id */
            id: number;
            /**
             * Status
             * @constant
             */
            status: "resolved";
        };
        /** ReviewerAgreement */
        ReviewerAgreement: {
            /** Agreed */
            agreed: number;
            /**
             * Rate
             * @description Share of human-reviewed requests where the reviewer kept the model's suggestion. Only requests the model was unsure about are reviewed, so this is NOT the model's overall accuracy.
             */
            rate: number | null;
            /** Resolved */
            resolved: number;
        };
        /** RouteRequest */
        RouteRequest: {
            /** Text */
            text: string;
        };
        /** RouteResponse */
        RouteResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "accepted" | "human_review";
            /** Confidence */
            confidence: number;
            /** Cost Usd */
            cost_usd: number;
            /** Degraded */
            degraded: boolean;
            /** Label */
            label: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Request Id */
            request_id: number;
            /** Tier */
            tier: string | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Accepted By Tier */
            accepted_by_tier: {
                [key: string]: number;
            };
            /** Cost Usd */
            cost_usd: number;
            /** Degraded */
            degraded: number;
            delivery: components["schemas"]["DeliveryCounts"];
            /** Human Review */
            human_review: number;
            latency_ms: components["schemas"]["LatencyStats"];
            /** Requests */
            requests: number;
            review: components["schemas"]["ReviewCounts"];
            reviewer_agreement: components["schemas"]["ReviewerAgreement"];
        };
        /** TierInfo */
        TierInfo: {
            /** Accept Threshold */
            accept_threshold: number;
            /** Model */
            model: string | null;
            /** Model Id */
            model_id: string | null;
            /** Name */
            name: string;
        };
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /** Accepted */
            accepted: number;
            /** Avg Latency Ms */
            avg_latency_ms: number;
            /** Cost Usd */
            cost_usd: number;
            /** Human Review */
            human_review: number;
            /** Requests */
            requests: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** TimeseriesResponse */
        TimeseriesResponse: {
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "hour" | "day";
            /** Points */
            points: components["schemas"]["TimeseriesPoint"][];
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Until
             * Format: date-time
             */
            until: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    retry_deliveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResult"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_requests: {
        parameters: {
            query?: {
                action?: ("accepted" | "human_review") | null;
                tier?: string | null;
                review_status?: ("pending" | "resolved") | null;
                delivery_status?: ("pending" | "sent" | "failed") | null;
                degraded?: boolean | null;
                q?: string | null;
                limit?: number;
                offset?: number;
                order?: "newest" | "oldest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Number of requests matching the filters, ignoring limit and offset */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Number of requests pending review, ignoring limit */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResolved"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries: {
        parameters: {
            query?: {
                bucket?: "hour" | "day";
                since?: string | null;
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
